version: '3.8'
services:

  # -----------------------
  # Laravel Backend
  # -----------------------
  laravel:
    build:
      context: ../auth-system
      dockerfile: Dockerfile
    volumes:
      # Editable folders
      - ../auth-system/app:/var/www/html/portfolio/auth-system/app:cached
      - ../auth-system/routes:/var/www/html/portfolio/auth-system/routes:cached
      - ../auth-system/config:/var/www/html/portfolio/auth-system/config:cached
      - ../auth-system/graphql:/var/www/html/portfolio/auth-system/graphql:cached
      # Storage handled by container
      - /var/www/html/portfolio/auth-system/storage
    expose:
      - "9000"
    env_file:
      - ../auth-system/.env
    networks:
      - appnet
      - proxy
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "php -v || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5

  # -----------------------
  # Laravel Worker
  # -----------------------
  laravel-worker:
    build:
      context: ../auth-system
      dockerfile: Dockerfile
    command: php artisan queue:work --queue=domain-events,default --sleep=1 --tries=5
    restart: always
    volumes:
      - ../auth-system/app:/var/www/html/portfolio/auth-system/app:cached
      - /var/www/html/portfolio/auth-system/storage
    env_file:
      - ../auth-system/.env
    networks:
      - appnet
      - proxy
    depends_on:
      laravel:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
  # -----------------------
  # Nginx
  # -----------------------
  # nginx:
  #   image: nginx:alpine
  #   restart: always
  #   volumes:
  #     - ../auth-system:/var/www/html/portfolio/auth-system:cached
  #     - ./nginx/sites-available/kayzinkhine.com.conf:/etc/nginx/conf.d/kayzinkhine.com.conf:ro
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - laravel
  #   networks:
  #     - appnet
  #     - proxy
  vue:
    build:
      context: ../vue-auth-system
      dockerfile: Dockerfile
    volumes:
      - ../vue-auth-system/src:/app/src:cached
      - ../vue-auth-system/tests:/app/tests:cached
    ports:
      - "${VITE_PORT:-5173}:5173"
    env_file:
      - ../vue-auth-system/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host 0.0.0.0
    networks:
      - appnet
      - proxy

  # -----------------------
  # MySQL
  # -----------------------
  mysql:
    image: mysql:8.0
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
    networks:
      - appnet
      - proxy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-u${DB_USERNAME:-root}", "-p${DB_PASSWORD:-root}"]
      interval: 10s
      timeout: 5s
      retries: 10

  # -----------------------
  # Mongo
  # -----------------------
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: StrongPassword123
    volumes:
      - portfolio_mongo_data:/data/db
    networks:
      - appnet
      - proxy
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 10

  # -----------------------
  # RabbitMQ
  # -----------------------
  rabbitmq:
    image: rabbitmq:3-management
    expose:
      - "5672"
    ports:
      - "${RABBITMQ_UI_PORT:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - appnet
      - proxy
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10

  # -----------------------
  # phpMyAdmin
  # -----------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    networks:
      - appnet
      - proxy

volumes:
  mysql_data:
  portfolio_mongo_data:
  rabbitmq_data:
  node_modules_vue:

networks:
  appnet:
  proxy:
    external: true